# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuFFEventPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('public_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'StuFF Event Pricing',
                'verbose_name_plural': 'StuFF Event Pricing',
            },
        ),
        migrations.CreateModel(
            name='StuFFPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('public_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'StuFF Pricing',
                'verbose_name_plural': 'StuFF Pricing',
            },
        ),
    ]
