# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('public_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
                ('matinee_freshers_price', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('matinee_freshers_nnt_price', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('allow_season_tickets', models.BooleanField(default=True)),
                ('allow_fellow_tickets', models.BooleanField(default=True)),
                ('allow_half_matinee', models.BooleanField(default=True)),
                ('allow_half_nnt_matinee', models.BooleanField(default=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Show')),
            ],
            options={
                'verbose_name': 'External Pricing',
                'verbose_name_plural': 'External Pricing',
            },
        ),
        migrations.CreateModel(
            name='FringePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fringe_price', models.DecimalField(decimal_places=2, default=3.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Fringe Pricing',
                'verbose_name_plural': 'Fringe Pricing',
            },
        ),
        migrations.CreateModel(
            name='InHousePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('public_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
                ('matinee_freshers_price', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('matinee_freshers_nnt_price', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'In House Pricing',
                'verbose_name_plural': 'In House Pricing',
            },
        ),
        migrations.CreateModel(
            name='SeasonTicketPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Season Ticket Pricing',
                'verbose_name_plural': 'Season Ticket Pricing',
            },
        ),
        migrations.CreateModel(
            name='StuFFEventPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('public_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Show')),
            ],
            options={
                'verbose_name': 'StuFF Event Pricing',
                'verbose_name_plural': 'StuFF Event Pricing',
            },
        ),
        migrations.CreateModel(
            name='StuFFPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('public_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('member_price', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Show')),
            ],
            options={
                'verbose_name': 'StuFF Pricing',
                'verbose_name_plural': 'StuFF Pricing',
            },
        ),
    ]
