# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonticketpricing',
            old_name='season_ticket_price',
            new_name='season_sale_nnt_price',
        ),
        migrations.RenameField(
            model_name='seasonticketpricing',
            old_name='season_ticket_price_nnt',
            new_name='season_sale_price',
        ),
    ]
