# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuffpricing',
            old_name='concession_price',
            new_name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='stuffpricing',
            name='member_price',
        ),
        migrations.RemoveField(
            model_name='stuffpricing',
            name='public_price',
        ),
    ]
