# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_externalpricing_fringepricing_inhousepricing_seasonticketpricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inhousepricing',
            name='season_ticket_price',
        ),
    ]
