# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20161021_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuFFPassPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_pass', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('festival_pass', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'StuFF Pass',
                'verbose_name_plural': 'StuFF Passes',
            },
        ),
        migrations.AlterField(
            model_name='stuffpricing',
            name='stuff_price',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6),
        ),
    ]
