# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20160404_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuffpricing',
            old_name='ticket_price',
            new_name='stuff_price',
        ),
        migrations.AddField(
            model_name='stuffeventpricing',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
