# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_inhousepricing_season_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fringepricing',
            name='concession_price',
        ),
        migrations.RemoveField(
            model_name='fringepricing',
            name='member_price',
        ),
        migrations.RemoveField(
            model_name='fringepricing',
            name='public_price',
        ),
        migrations.AddField(
            model_name='fringepricing',
            name='fringe_price',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6),
        ),
    ]
