# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20160404_1715'),
        ('pricing', '0002_seasonticketpricing_season_ticket_price_nnt'),
    ]

    operations = [
    ]
