# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpricing',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inhousepricing',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='seasonticketpricing',
            name='season_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='seasonticketpricing',
            name='season_ticket_price_nnt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stuffeventpricing',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
