# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_auto_20151229_0955'),
        ('pricing', '0004_auto_20151228_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffeventpricing',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.Show'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuffpricing',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.Show'),
            preserve_default=False,
        ),
    ]
