# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20151229_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpricing',
            name='matinee_freshers_nnt_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='externalpricing',
            name='matinee_freshers_price',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6),
        ),
    ]
