# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(help_text=b'A short description, in 140 characters or less.', max_length=140),
        ),
        migrations.AlterField(
            model_name='show',
            name='long_description',
            field=models.TextField(blank=True, help_text=b'Shows up on the detail page, this field is written in Markdown. (See <a href="http://www.darkcoding.net/software/markdown-quick-reference/">Markdown reference</a> for reference).'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'sort')]),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together=set([('show', 'date', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set([('name', 'start_date', 'end_date')]),
        ),
    ]
