# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number_season_sale_nnt',
            field=models.IntegerField(default=0),
        ),
    ]
