# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_sale_number_stuff'),
        ('tickets', '0002_sale_number_season_sale_nnt'),
    ]

    operations = [
    ]
