# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20151217_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='unique_code',
            field=models.CharField(default='null', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='time',
            field=models.TimeField(default=datetime.time(19, 30)),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
