# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20161016_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
