# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20161024_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(help_text=b'A short description'),
        ),
    ]
