# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
