# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-31 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20161024_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'The name of the warning', max_length=100)),
                ('icon', models.CharField(help_text=b'An icon code, from this list: https://material.io/icons/', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='warnings',
            field=models.ManyToManyField(default=None, to='tickets.Warnings'),
        ),
    ]
