# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20171031_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='number_day_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='number_festival',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='number_festival_sales',
            field=models.IntegerField(default=0),
        ),
    ]
