# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180608_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'The name of the warning', max_length=100)),
                ('icon', models.CharField(blank=True, help_text=b'An icon code, from this list: https://material.io/icons/', max_length=50)),
                ('category', models.CharField(choices=[(b'1', b'Technical Effects'), (b'2', b'Content')], default=b'2', max_length=50)),
            ],
            options={
                'verbose_name': 'Content Warning',
                'verbose_name_plural': 'Content Warnings',
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='warnings',
        ),
        migrations.AddField(
            model_name='show',
            name='warnings_notes',
            field=models.TextField(blank=True, help_text=b'Description of any content warnings. Visible to Front of House only.'),
        ),
        migrations.DeleteModel(
            name='Warnings',
        ),
        migrations.AddField(
            model_name='show',
            name='warnings_action',
            field=models.ManyToManyField(blank=True, related_name='warnings_action', to='tickets.ContentWarning', verbose_name=b'Scenes of...'),
        ),
        migrations.AddField(
            model_name='show',
            name='warnings_dialogue',
            field=models.ManyToManyField(blank=True, related_name='warnings_dialogue', to='tickets.ContentWarning', verbose_name=b'Discussions / themes of...'),
        ),
        migrations.AddField(
            model_name='show',
            name='warnings_technical',
            field=models.ManyToManyField(blank=True, related_name='warnings_technical', to='tickets.ContentWarning', verbose_name=b'Technical Warnings'),
        ),
    ]
