# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20151220_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now=True)),
                ('unique_code', models.CharField(max_length=16)),
                ('number_members', models.IntegerField(default=1)),
                ('number_public', models.IntegerField(default=1)),
                ('number_comp', models.IntegerField(default=1)),
                ('number_fellow', models.IntegerField(default=1)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Occurrence')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
