# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-05-11 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20171031_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warnings',
            options={'verbose_name': 'Content Warning', 'verbose_name_plural': 'Content Warnings'},
        ),
        migrations.AddField(
            model_name='warnings',
            name='category',
            field=models.CharField(choices=[(b'A', b'Action'), (b'D', b'Dialogue'), (b'T', b'Technical Effects')], default=b'A', max_length=50),
        ),
        migrations.AddField(
            model_name='warnings',
            name='visible',
            field=models.BooleanField(default=False, help_text=b'Whether this is visible to audiences (all are visible to FOH).'),
        ),
        migrations.AlterField(
            model_name='show',
            name='warnings',
            field=models.ManyToManyField(blank=True, to='tickets.Warnings'),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='icon',
            field=models.CharField(blank=True, help_text=b'An icon code, from this list: https://material.io/icons/', max_length=50),
        ),
    ]
