# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190511_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='visible',
            field=models.BooleanField(default=True, help_text=b'Whether this is visible to audiences (all are visible to FOH).'),
        ),
    ]
