# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190517_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='no_warnings',
            field=models.BooleanField(default=False, help_text=b'Select True if a show has no content warnings.'),
        ),
        migrations.AddField(
            model_name='show',
            name='programme',
            field=models.URLField(blank=True, help_text=b'Link to a page or PDF hosting a programme. Try hosting it on Google Drive or <a href="https://github.com/newtheatre/history-project/tree/master/assets/for_shows" target="_blank">Github</a>.', null=True),
        ),
    ]
