# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190511_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='warnings_notes',
            field=models.TextField(blank=True, help_text=b'Description of any content warnings. Visible to Front of House only.'),
        ),
    ]
