# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20151224_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='number_comp',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='number_members',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='occurrence',
        ),
        migrations.AddField(
            model_name='sale',
            name='number_concession',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='number_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_fellow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_public',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
