# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_show_warnings_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='category',
            field=models.CharField(choices=[(b'T', b'Technical Effects'), (b'A', b'Action'), (b'D', b'Dialogue')], default=b'A', max_length=50),
        ),
    ]
