# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190511_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
