# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20151224_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='occurrence',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, to='tickets.Occurrence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
