# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190613_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number_performer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='number_performer_sales',
            field=models.IntegerField(default=0),
        ),
    ]
