# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190613_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='external_link',
            field=models.URLField(blank=True),
        ),
    ]
