# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20190511_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='category',
            field=models.CharField(choices=[(b'1', b'Technical Effects'), (b'2', b'Action'), (b'3', b'Dialogue')], default=b'2', max_length=50),
        ),
    ]
