# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20190627_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='external_link',
            field=models.URLField(blank=True, help_text=b"Link to an external booking website; overrides NT reservation capability. Don't forget the 'http://'!"),
        ),
    ]
