# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20151224_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster_report',
            field=models.ImageField(blank=True, null=True, upload_to=b'posters'),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
