# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20190511_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'The name of the warning', max_length=100)),
                ('icon', models.CharField(blank=True, help_text=b'An icon code, from this list: https://material.io/icons/', max_length=50)),
                ('category', models.CharField(choices=[(b'1', b'Technical Effects'), (b'2', b'Action'), (b'3', b'Dialogue')], default=b'2', max_length=50)),
            ],
            options={
                'verbose_name': 'Content Warning',
                'verbose_name_plural': 'Content Warnings',
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='warnings',
        ),
        migrations.DeleteModel(
            name='Warnings',
        ),
        migrations.AddField(
            model_name='show',
            name='warnings_technical',
            field=models.ManyToManyField(blank=True, to='tickets.Content_Warning'),
        ),
    ]
