# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-11 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_show_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email_address',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='person_name',
            field=models.CharField(max_length=200),
        ),
    ]
