# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20190514_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content_Warning',
            new_name='ContentWarning',
        ),
    ]
