# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20190514_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='warnings_action',
            field=models.ManyToManyField(blank=True, related_name='warnings_action', to='tickets.ContentWarning', verbose_name=b'Action-based Warnings'),
        ),
        migrations.AlterField(
            model_name='show',
            name='warnings_dialogue',
            field=models.ManyToManyField(blank=True, related_name='warnings_dialogue', to='tickets.ContentWarning', verbose_name=b'Dialogue-based Warnings'),
        ),
        migrations.AlterField(
            model_name='show',
            name='warnings_technical',
            field=models.ManyToManyField(blank=True, related_name='warnings_technical', to='tickets.ContentWarning', verbose_name=b'Technical Warnings'),
        ),
    ]
