# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20190514_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='warnings_action',
            field=models.ManyToManyField(blank=True, help_text=b'Things that are seen on-stage', related_name='warnings_action', to='tickets.ContentWarning', verbose_name=b'Action-based Warnings'),
        ),
        migrations.AlterField(
            model_name='show',
            name='warnings_dialogue',
            field=models.ManyToManyField(blank=True, help_text=b'Discussions / themes of...', related_name='warnings_dialogue', to='tickets.ContentWarning', verbose_name=b'Dialogue-based Warnings'),
        ),
    ]
