# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20190514_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='warnings_action',
            field=models.ManyToManyField(blank=True, related_name='warnings_action', to='tickets.ContentWarning', verbose_name=b'Scenes of...'),
        ),
        migrations.AlterField(
            model_name='show',
            name='warnings_dialogue',
            field=models.ManyToManyField(blank=True, related_name='warnings_dialogue', to='tickets.ContentWarning', verbose_name=b'Discussions / themes of...'),
        ),
    ]
