# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20190514_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwarning',
            name='category',
            field=models.CharField(choices=[(b'1', b'Technical Effects'), (b'2', b'Content')], default=b'2', max_length=50),
        ),
    ]
