# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_auto_20151225_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='number_mat_freshers',
            new_name='number_matinee_freshers',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='number_mat_freshers_nnt',
            new_name='number_matinee_freshers_nnt',
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
