# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_auto_20151225_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
