# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_auto_20151225_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_price', models.IntegerField()),
                ('public_price', models.IntegerField()),
                ('allow_season_tickets', models.BooleanField(default=True)),
                ('allow_fellow_tickets', models.BooleanField(default=True)),
                ('allow_half_matinee', models.BooleanField(default=True)),
                ('allow_half_nnt_matinee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'External Pricing',
                'verbose_name_plural': 'External Pricing',
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
        migrations.AddField(
            model_name='externalpricing',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Show'),
        ),
    ]
