# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_auto_20151226_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpricing',
            name='member_price',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='number_member',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
