# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_auto_20151226_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[(b'IN_HOUSE', b'In House'), (b'FRINGE', b'Fringe'), (b'EXTERNAL', b'External'), (b'STUFF', b'StuFF'), (b'STUFF_EVENTS', b'StuFF Events')], default='IN_HOUSE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
