# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_auto_20151226_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTicketPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Season Ticket Pricing',
                'verbose_name_plural': 'Season Ticket Pricing',
            },
        ),
        migrations.RemoveField(
            model_name='externalpricing',
            name='season_ticket_price',
        ),
        migrations.RemoveField(
            model_name='fringepricing',
            name='season_ticket_price',
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
