# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_auto_20151227_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='number_external',
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
