# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_auto_20151229_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(help_text=b'Low to high, sorts the sidebar.', validators=[django.core.validators.MinValueValidator(6, b'Minimum values is 6')]),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
