# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_auto_20151230_1811'),
        ('tickets', '0007_auto_20160101_2335'),
    ]

    operations = [
    ]
