# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0054_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='poster_page',
        ),
        migrations.RemoveField(
            model_name='show',
            name='poster_tiny',
        ),
        migrations.RemoveField(
            model_name='show',
            name='poster_wall',
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_concession',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_fellow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_fringe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_matinee_freshers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_matinee_freshers_nnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_member',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_public',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number_season_sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=stdimage.models.StdImageField(blank=True, help_text=b'Upload a large image, we will automatically create smaller versions to use.', null=True, upload_to=stdimage.utils.UploadToClassNameDir()),
        ),
    ]
